services:
    - docker
language: go
dist: trusty
os:
    - linux
go:
    - 1.10.x
go_import_path: github.com/kdruelle/purge-manager
install:
    - go get github.com/karalabe/xgo
    - docker pull karalabe/xgo-latest
    - go get github.com/goreleaser/nfpm/cmd/nfpm
    - go get -u github.com/golang/dep/cmd/dep
    - dep ensure
script:
    - make ci
addons:
  apt:
    packages:
    - rpm
before_deploy:
    - cd $TRAVIS_BUILD_DIR
    - ls ./
    - ls dist/*
deploy:
    skip_cleanup: true
    provider: releases
    api_key:
        secure: nlojUrwa5CwBXKK/4rLJftn9Vq6pywbhpoHfvSIMSmhziCS0nYSq/pl+cfO/NYpriLm4rgd4EBmXvZJNXOxDJp5VJ4pqgt910W2h0mumzn1UrDP6cGuMcrr9yJvVa881B5U6eH8ZLRKjbtfF4CV+ZYh8U3KFNToNfYfPPcx5jR/yT/HrLygtt2Nr1cgl+IQz2xKi5JIt0qspaX3QXyzN0ZMMz2j4DQofHVzCrrI3eDbDRhXhV65c+VraovXMs6mLDW0fpD3X0/eSTGY61ZruNoQcvbn/4JwsFiVVYB4h3SR1F0HVUvoOHLsUa/K9SLhX2kOqTQWXlut9GxlI+D6+EPUGMfsMm5/wg8ljcqpf0VeO+Y6qqjU1Fe6TsjPXfgDJLwzs1BuQmrQFdnS6QJ1zcNk8u9Nis5GiiO7Dtw0oWlzQwgoVchA3mlZ47Susn+3UbzYIPqWLsih0L8l55muyITYxfoK8XSlWBr982pr60BQXQkXsQIR1lR4BehJYGvbWhgW7DaQ6k24SNWUwzrptvkOygZTHuRP4tOFbHSvMxDW+0P6HC9yaOb9ZKxjSYXnV++sadYi3I2NgTvmDj75qu3wm7R8VP1AXHfbLXC8pgAHmigyfzCv7Y8vgyHdMhQ8FDXZW1rRDxjgnFMrx02PpCPjCAhScS5gg6voBBCNKxLY=
    file_glob: true
    file: 
        - dist/*
    on:
        tags: true
